
server:

  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true


spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    password: 1234
    username: nulljeju

  jpa:

    open-in-view: true
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate.format_sql: true

  jackson:
    serialization:
      fail-on-empty-beans: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: jejumarureply@gmail.com
    password: jejumaru1234
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


